export const ATTIVITA = {
  ACQUISTI: "ACQUISTI",
  TRASFERTA: "TRASFERTA",
  MAGAZZINO: "MAGAZZINO",
  UFFICIO: "UFFICIO",
  SOPRALLUOGO: "SOPRALLUOGO",
  ASSISTENZA: "ASSISTENZA",
  VISITA_MEDICA: "VISITA_MEDICA",
  FORMAZIONE: "FORMAZIONE",
  ALTRO: "ALTRO",
} as const;
